from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1299, 715)
        MainWindow.setMinimumSize(QtCore.QSize(1299, 685))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setStyleSheet("title {background-color: #A1B3B0;}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(1294, 680))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setStyleSheet("background-color: #1a1a1a;")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_4.setContentsMargins(5, 10, 5, 10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Framemain = QtWidgets.QLabel(self.centralwidget)
        self.Framemain.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Framemain.sizePolicy().hasHeightForWidth())
        self.Framemain.setSizePolicy(sizePolicy)
        self.Framemain.setMaximumSize(QtCore.QSize(16777215, 16777213))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.Framemain.setFont(font)
        self.Framemain.setFrameShape(QtWidgets.QFrame.Panel)
        self.Framemain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Framemain.setLineWidth(2)
        self.Framemain.setStyleSheet("border: 2px solid #00FFFF;")
        self.Framemain.setText("")
        self.Framemain.setObjectName("Framemain")
        self.verticalLayout_4.addWidget(self.Framemain)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_9.setContentsMargins(-1, -1, -1, 6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.webcam = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webcam.sizePolicy().hasHeightForWidth())
        self.webcam.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 163, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 163, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 163, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        self.webcam.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.webcam.setFont(font)
        self.webcam.setStyleSheet("background-color: #009999;")
        self.webcam.setAutoDefault(False)
        self.webcam.setObjectName("webcam")
        self.horizontalLayout_9.addWidget(self.webcam)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.capture = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.capture.sizePolicy().hasHeightForWidth())
        self.capture.setSizePolicy(sizePolicy)
        self.capture.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.capture.setFont(font)
        self.capture.setAutoDefault(False)
        self.capture.setObjectName("capture")
        self.capture.setStyleSheet("background-color: #009999;")
        self.horizontalLayout_9.addWidget(self.capture)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.weld_count = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.weld_count.setFont(font)
        self.weld_count.setObjectName("weld_count")
        self.weld_count.setStyleSheet("color: #009999;")
        self.horizontalLayout_9.addWidget(self.weld_count)
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setBaseSize(QtCore.QSize(0, 0))
        self.spinBox.setStyleSheet("color: #009999;")
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox.setFont(font)
        self.spinBox.setWrapping(False)
        self.spinBox.setReadOnly(False)
        self.spinBox.setAccelerated(True)
        self.spinBox.setKeyboardTracking(True)
        self.spinBox.setProperty("showGroupSeparator", False)
        self.spinBox.setMaximum(10)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_9.addWidget(self.spinBox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.horizontalLayout_9.setStretch(0, 1)
        self.horizontalLayout_9.setStretch(1, 2)
        self.horizontalLayout_9.setStretch(2, 1)
        self.horizontalLayout_9.setStretch(3, 2)
        self.horizontalLayout_9.setStretch(4, 1)
        self.horizontalLayout_9.setStretch(5, 1)
        self.horizontalLayout_9.setStretch(7, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(20, -1, 0, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.notify_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.notify_label.setFont(font)
        self.notify_label.setObjectName("notify_label")
        self.notify_label.setStyleSheet("color: white;")
        self.horizontalLayout_4.addWidget(self.notify_label)
        self.notify = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.notify.setFont(font)
        self.notify.setObjectName("notify")
        self.notify.setStyleSheet("color: white;")
        self.horizontalLayout_4.addWidget(self.notify)
        self.horizontalLayout_4.setStretch(1, 8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.setStretch(0, 9)
        self.verticalLayout_2.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_5.setContentsMargins(-1, 6, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.Frame1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Frame1.sizePolicy().hasHeightForWidth())
        self.Frame1.setSizePolicy(sizePolicy)
        self.Frame1.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Frame1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Frame1.setText("")
        self.Frame1.setObjectName("Frame1")
        self.Frame1.setStyleSheet("border: 2px solid #00FFFF;")
        self.verticalLayout_9.addWidget(self.Frame1)
        self.horizontalLayout_8.addLayout(self.verticalLayout_9)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label.setStyleSheet("color: white;")
        self.label.setMinimumSize(QtCore.QSize(85, 20))
        self.verticalLayout_6.addWidget(self.label)
        self.score1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.score1.setFont(font)
        self.score1.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.score1.setObjectName("score1")
        self.score1.setStyleSheet("border: 2px solid #00FFFF; color: white;")
        self.score1.setMinimumSize(QtCore.QSize(85, 81))
        self.verticalLayout_6.addWidget(self.score1)
        self.verticalLayout_6.setStretch(0, 2)
        self.verticalLayout_6.setStretch(1, 8)
        self.horizontalLayout_8.addLayout(self.verticalLayout_6)
        self.horizontalLayout_8.setStretch(0, 9)
        self.horizontalLayout_8.setStretch(1, 1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.Frame2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Frame2.sizePolicy().hasHeightForWidth())
        self.Frame2.setSizePolicy(sizePolicy)
        self.Frame2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Frame2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Frame2.setText("")
        self.Frame2.setObjectName("Frame2")
        self.Frame2.setStyleSheet("border: 2px solid #00FFFF;")
        self.verticalLayout_10.addWidget(self.Frame2)
        self.horizontalLayout_14.addLayout(self.verticalLayout_10)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_2.setStyleSheet("color: white;")
        self.label_2.setMinimumSize(QtCore.QSize(85, 20))
        self.verticalLayout_8.addWidget(self.label_2)
        self.score2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.score2.setFont(font)
        self.score2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.score2.setObjectName("score2")
        self.score2.setStyleSheet("border: 2px solid #00FFFF; color: white;")
        self.score2.setMinimumSize(QtCore.QSize(85, 81))
        self.verticalLayout_8.addWidget(self.score2)
        self.verticalLayout_8.setStretch(0, 2)
        self.verticalLayout_8.setStretch(1, 8)
        self.horizontalLayout_14.addLayout(self.verticalLayout_8)
        self.horizontalLayout_14.setStretch(0, 9)
        self.horizontalLayout_14.setStretch(1, 1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.Frame3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Frame3.sizePolicy().hasHeightForWidth())
        self.Frame3.setSizePolicy(sizePolicy)
        self.Frame3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Frame3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Frame3.setText("")
        self.Frame3.setObjectName("Frame3")
        self.Frame3.setStyleSheet("border: 2px solid #00FFFF;")
        self.verticalLayout_12.addWidget(self.Frame3)
        self.horizontalLayout_15.addLayout(self.verticalLayout_12)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_3.setStyleSheet("color: white;")
        self.label_3.setMinimumSize(QtCore.QSize(85, 20))
        self.verticalLayout_11.addWidget(self.label_3)
        self.score3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.score3.setFont(font)
        self.score3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.score3.setObjectName("score3")
        self.score3.setStyleSheet("border: 2px solid #00FFFF; color: white;")
        self.score3.setMinimumSize(QtCore.QSize(85, 81))
        self.verticalLayout_11.addWidget(self.score3)
        self.verticalLayout_11.setStretch(0, 2)
        self.verticalLayout_11.setStretch(1, 8)
        self.horizontalLayout_15.addLayout(self.verticalLayout_11)
        self.horizontalLayout_15.setStretch(0, 9)
        self.horizontalLayout_15.setStretch(1, 1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.Frame4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Frame4.sizePolicy().hasHeightForWidth())
        self.Frame4.setSizePolicy(sizePolicy)
        self.Frame4.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Frame4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Frame4.setText("")
        self.Frame4.setObjectName("Frame4")
        self.Frame4.setStyleSheet("border: 2px solid #00FFFF;")
        self.verticalLayout_14.addWidget(self.Frame4)
        self.horizontalLayout_16.addLayout(self.verticalLayout_14)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_4.setStyleSheet("color: white;")
        self.label_4.setMinimumSize(QtCore.QSize(85, 20))
        self.verticalLayout_13.addWidget(self.label_4)
        self.score4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.score4.setFont(font)
        self.score4.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.score4.setObjectName("score4")
        self.score4.setStyleSheet("border: 2px solid #00FFFF; color: white;")
        self.score4.setMinimumSize(QtCore.QSize(85, 81))
        self.verticalLayout_13.addWidget(self.score4)
        self.verticalLayout_13.setStretch(0, 2)
        self.verticalLayout_13.setStretch(1, 8)
        self.horizontalLayout_16.addLayout(self.verticalLayout_13)
        self.horizontalLayout_16.setStretch(0, 9)
        self.horizontalLayout_16.setStretch(1, 1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.Frame5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Frame5.sizePolicy().hasHeightForWidth())
        self.Frame5.setSizePolicy(sizePolicy)
        self.Frame5.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Frame5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Frame5.setText("")
        self.Frame5.setObjectName("Frame5")
        self.Frame5.setStyleSheet("border: 2px solid #00FFFF;")
        self.verticalLayout_18.addWidget(self.Frame5)
        self.horizontalLayout_18.addLayout(self.verticalLayout_18)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setObjectName("label_5")
        self.label_5.setStyleSheet("color: white;")
        self.label_5.setMinimumSize(QtCore.QSize(85, 20))
        self.verticalLayout_15.addWidget(self.label_5)
        self.score5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.score5.setFont(font)
        self.score5.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.score5.setObjectName("score5")
        self.score5.setStyleSheet("border: 2px solid #00FFFF; color: white;")
        self.score5.setMinimumSize(QtCore.QSize(85, 81))
        self.verticalLayout_15.addWidget(self.score5)
        self.verticalLayout_15.setStretch(0, 2)
        self.verticalLayout_15.setStretch(1, 8)
        self.horizontalLayout_18.addLayout(self.verticalLayout_15)
        self.horizontalLayout_18.setStretch(0, 9)
        self.horizontalLayout_18.setStretch(1, 1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_18)
        self.verticalLayout_7.setStretch(0, 1)
        self.verticalLayout_7.setStretch(1, 1)
        self.verticalLayout_7.setStretch(2, 1)
        self.verticalLayout_7.setStretch(3, 1)
        self.verticalLayout_7.setStretch(4, 1)
        self.verticalLayout_5.addLayout(self.verticalLayout_7)
        self.verticalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem4)
        self.save = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save.sizePolicy().hasHeightForWidth())
        self.save.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.save.setFont(font)
        self.save.setCheckable(False)
        self.save.setAutoRepeatDelay(300)
        self.save.setAutoDefault(False)
        self.save.setDefault(False)
        self.save.setFlat(False)
        self.save.setObjectName("save")
        self.save.setStyleSheet("background: #009999;")
        self.horizontalLayout_13.addWidget(self.save)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem5)
        self.reset = QtWidgets.QPushButton(self.centralwidget)
        self.reset.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset.sizePolicy().hasHeightForWidth())
        self.reset.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.reset.setFont(font)
        self.reset.setMouseTracking(False)
        self.reset.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.reset.setAutoFillBackground(False)
        self.reset.setIconSize(QtCore.QSize(16, 16))
        self.reset.setAutoDefault(False)
        self.reset.setDefault(False)
        self.reset.setFlat(False)
        self.reset.setObjectName("reset")
        self.reset.setStyleSheet("background: #009999;")
        self.horizontalLayout_13.addWidget(self.reset)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem6)
        self.Score = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Score.sizePolicy().hasHeightForWidth())
        self.Score.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Score.setFont(font)
        self.Score.setAutoRepeat(False)
        self.Score.setAutoExclusive(False)
        self.Score.setAutoDefault(False)
        self.Score.setDefault(False)
        self.Score.setFlat(False)
        self.Score.setObjectName("Score")
        self.Score.setStyleSheet("background: #009999;")
        self.horizontalLayout_13.addWidget(self.Score)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem7)
        self.horizontalLayout_13.setStretch(1, 2)
        self.horizontalLayout_13.setStretch(3, 2)
        self.horizontalLayout_13.setStretch(5, 2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setContentsMargins(8, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Save_address = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Save_address.setFont(font)
        self.Save_address.setObjectName("Save_address")
        self.Save_address.setStyleSheet("color: #cccccc;")
        self.horizontalLayout_2.addWidget(self.Save_address)
        self.save_address = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_address.sizePolicy().hasHeightForWidth())
        self.save_address.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.save_address.setFont(font)
        self.save_address.setObjectName("save_address")
        self.save_address.setStyleSheet("color: #cccccc;")
        self.horizontalLayout_2.addWidget(self.save_address)
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setInputMethodHints(QtCore.Qt.ImhNone)
        self.toolButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Capture.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon1)
        self.toolButton.setIconSize(QtCore.QSize(20, 20))
        self.toolButton.setCheckable(False)
        self.toolButton.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.toolButton.setAutoRaise(True)
        self.toolButton.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_2.addWidget(self.toolButton)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.setStretch(0, 7)
        self.verticalLayout_3.setStretch(1, 3)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout.setStretch(0, 9)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 6)
        self.horizontalLayout.setStretch(1, 5)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CDWeld"))
        self.webcam.setText(_translate("MainWindow", "CAMERA"))
        self.capture.setText(_translate("MainWindow", "CAPTURE"))
        self.weld_count.setText(_translate("MainWindow", "PLATES :"))
        self.notify_label.setText(_translate("MainWindow", "Notify: "))
        self.notify.setText(_translate("MainWindow", "Please turn on Camera and enter Capture"))
        self.label.setText(_translate("MainWindow", "    Assess"))
        self.score1.setText(_translate("MainWindow", ""))
        self.label_2.setText(_translate("MainWindow", "    Assess"))
        self.score2.setText(_translate("MainWindow", ""))
        self.label_3.setText(_translate("MainWindow", "    Assess"))
        self.score3.setText(_translate("MainWindow", ""))
        self.label_4.setText(_translate("MainWindow", "    Assess"))
        self.score4.setText(_translate("MainWindow", ""))
        self.label_5.setText(_translate("MainWindow", "    Assess"))
        self.score5.setText(_translate("MainWindow", ""))
        self.save.setText(_translate("MainWindow", "SAVE"))
        self.reset.setText(_translate("MainWindow", "RESET"))
        self.Score.setText(_translate("MainWindow", "ASSESS"))
        self.Save_address.setText(_translate("MainWindow", "Save address:"))
        self.save_address.setText(_translate("MainWindow", "Select folder save data"))



